const styles = {
  dashboard: {
    position: 'fixed',
    height: '100vh',
    width: '100vw',
    top: '-30px',
    left: '300px',
    backgroundColor: '#F4F7F8',
    padding: '20px',
    fontFamily: "Plus Jakarta Sans, sans-serif",
    overflowY: 'auto',
  },
  dashboardHeader: {
    fontFamily: "Plus Jakarta Sans, sans-serif",
    fontSize: '1.5rem',
    color: '#212529',
    paddingLeft: '40px',
    fontWeight: 'bold',
  },
  dashboardContent: {
    display: 'flex',
    flexDirection: 'column',
    marginLeft: '10px',
    gap: '30px',
  },
  chartRow: {
    display: 'flex',
    gap: '30px',
    flexWrap: 'wrap',
    marginTop: '20px',
  },
  chartCard: {
    backgroundColor: '#fff',
    borderRadius: '25px',
    padding: '25px',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.05)',
    flex: '1 1 400px',
    minWidth: '320px',
    maxWidth: '38%',
    height: '10%',
    fontFamily: "Plus Jakarta Sans, sans-serif",
  },
  fullWidthChartCard: {
    backgroundColor: '#fff',
    borderRadius: '25px',
    padding: '25px',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.05)',
    width: '100%',
    minHeight: '380px',
    fontFamily: "Plus Jakarta Sans, sans-serif",
  },
  chartHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '20px',
  },
  chartWrapper: {
    width: '100%',
    height: '280px',
    overflow: 'hidden',
  },
  dropdownContainer: {
    position: 'relative',
    display: 'inline-block',
  },
  dropdown: {
    appearance: 'none',
    WebkitAppearance: 'none',
    MozAppearance: 'none',
    padding: '8px 32px 8px 16px',
    fontSize: '14px',
    fontWeight: '500',
    color: '#07715B',
    backgroundColor: '#f7f9fc',
    border: '1px solid #e1e4e8',
    borderRadius: '8px',
    boxShadow: '0 1px 2px rgba(0, 0, 0, 0.05)',
    cursor: 'pointer',
    backgroundImage: `url("data:image/svg+xml;charset=UTF-8,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='%2307715B' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3e%3cpolyline points='6 9 12 15 18 9'%3e%3c/polyline%3e%3c/svg%3e")`,
    backgroundRepeat: 'no-repeat',
    backgroundPosition: 'right 10px center',
    backgroundSize: '12px',
    transition: 'all 0.2s ease',
    outline: 'none',
    fontFamily: "Plus Jakarta Sans, sans-serif",
  },
  mapContainer: {
    width: '40%',
    height: '387px',
    borderRadius: '25px',
    overflow: 'hidden',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.05)',
  },
  headerText: {
    fontSize: '20px',
    color: '#333',
    fontWeight: '600',
    margin: 0,
    fontFamily: "Plus Jakarta Sans, sans-serif",
  },
  subtitleText: {
    fontSize: '14px',
    color: '#666',
    fontWeight: '400',
    margin: 0,
    fontFamily: "Plus Jakarta Sans, sans-serif",
  },
  // New styles for custom legend
  legendContainer: {
    display: 'flex',
    justifyContent: 'center',
    gap: '20px',
    marginTop: '15px',
  },
  legendItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  legendBox: {
    width: '16px',
    height: '16px',
  },
  legendText: {
    fontSize: '14px',
    color: '#555',
    fontFamily: "Plus Jakarta Sans, sans-serif",
  }
};

export default styles;